## **I. Packages importing**

In [1]:
import re

import pandas as pd

pd.options.display.max_columns = None

## **II. Data importing**

In [2]:
df = pd.read_csv(filepath_or_buffer='data/data.csv', skiprows=1)
df.head()

,Period,Product Type,Sales Office,Sales Volume (pieces),Gross Sales (đ),Gross Sales (USD),Raw Materials (raw cases - rcs),Packaging,Packaging (USD),Other Direct Cost (đ),Other Direct Cost (USD),Variable Manufacturing (đ),Variable Manufacturing (USD),Fixed Manufacturing (đ),Fixed Manufacturing (USD),Warehouse (đ),Warehouse (USD),Trans. Primary (đ),Trans. Primary (USD),Trans. Delivery (đ),Trans. Delivery (USD)
0,2022-M01,CAN CF,South,86.713,14.268.364.426,620.364,2.233.480.002,3.523.596.662,153.200,124.582.917,5.417,331.869.079,14.429,832.874.059,36.212,171.690.280,7.465,208.007.642,9.044,252.190.721,10.965
1,2022-M01,CAN CF,South,192.462,31.067.668.925,1.350.768,4.957.263.365,7.820.708.772,340.031,276.514.824,12.022,736.591.520,32.026,1.848.584.296,80.373,381.070.766,16.568,461.678.036,20.073,559.743.460,24.337
2,2022-M01,CAN CF,South,77.879,12.744.482.325,554.108,2.005.942.650,3.164.627.762,137.593,111.890.945,4.865,298.059.682,12.959,748.024.425,32.523,154.199.211,6.704,186.816.716,8.122,226.498.613,9.848
3,2022-M01,CAN CF,Central,132.807,21.611.233.161,939.619,3.420.718.705,5.396.615.595,234.635,190.806.775,8.296,508.278.904,22.099,1.275.600.349,55.461,262.954.739,11.433,318.577.122,13.851,386.246.358,16.793
4,2022-M01,CAN CF,North,27.914,4.718.876.991,205.169,718.979.125,1.134.280.334,49.317,40.104.464,1.744,106.831.912,4.645,268.110.330,11.657,55.268.785,2.403,66.959.700,2.911,81.182.667,3.530

## **III. Data Preprocessing**

### **1. Handle column names**

In [3]:
df.columns

Index(['Period', 'Product Type', 'Sales Office', ' Sales Volume (pieces) ',
       ' Gross Sales (đ) ', ' Gross Sales (USD) ',
       ' Raw Materials (raw cases - rcs) ', ' Packaging ', ' Packaging (USD) ',
       ' Other Direct Cost (đ) ', ' Other Direct Cost (USD) ',
       ' Variable Manufacturing (đ) ', ' Variable Manufacturing (USD) ',
       ' Fixed Manufacturing (đ) ', ' Fixed Manufacturing (USD) ',
       ' Warehouse (đ) ', ' Warehouse (USD) ', ' Trans. Primary (đ) ',
       ' Trans. Primary (USD) ', ' Trans. Delivery (đ) ',
       ' Trans. Delivery (USD) '],
      dtype='object')

In [4]:
df.columns = df.columns.str.strip()
df.drop(columns=[col for col in df.columns if 'đ' in col] + ['Packaging'], inplace=True)
df.head()

,Period,Product Type,Sales Office,Sales Volume (pieces),Gross Sales (USD),Raw Materials (raw cases - rcs),Packaging (USD),Other Direct Cost (USD),Variable Manufacturing (USD),Fixed Manufacturing (USD),Warehouse (USD),Trans. Primary (USD),Trans. Delivery (USD)
0,2022-M01,CAN CF,South,86.713,620.364,2.233.480.002,153.200,5.417,14.429,36.212,7.465,9.044,10.965
1,2022-M01,CAN CF,South,192.462,1.350.768,4.957.263.365,340.031,12.022,32.026,80.373,16.568,20.073,24.337
2,2022-M01,CAN CF,South,77.879,554.108,2.005.942.650,137.593,4.865,12.959,32.523,6.704,8.122,9.848
3,2022-M01,CAN CF,Central,132.807,939.619,3.420.718.705,234.635,8.296,22.099,55.461,11.433,13.851,16.793
4,2022-M01,CAN CF,North,27.914,205.169,718.979.125,49.317,1.744,4.645,11.657,2.403,2.911,3.530

In [5]:
df.columns = (df.columns.str.lower()
             .str.split(pat=r' \(').str[0]
             .str.replace(pat=' ', repl='_')
             .str.replace(pat='.', repl=''))
df.head()

,period,product_type,sales_office,sales_volume,gross_sales,raw_materials,packaging,other_direct_cost,variable_manufacturing,fixed_manufacturing,warehouse,trans_primary,trans_delivery
0,2022-M01,CAN CF,South,86.713,620.364,2.233.480.002,153.200,5.417,14.429,36.212,7.465,9.044,10.965
1,2022-M01,CAN CF,South,192.462,1.350.768,4.957.263.365,340.031,12.022,32.026,80.373,16.568,20.073,24.337
2,2022-M01,CAN CF,South,77.879,554.108,2.005.942.650,137.593,4.865,12.959,32.523,6.704,8.122,9.848
3,2022-M01,CAN CF,Central,132.807,939.619,3.420.718.705,234.635,8.296,22.099,55.461,11.433,13.851,16.793
4,2022-M01,CAN CF,North,27.914,205.169,718.979.125,49.317,1.744,4.645,11.657,2.403,2.911,3.530

### **2. Handle invalid values**

In [6]:
df = (df.apply(func=lambda x: x.str.strip().str.replace(pat='.', repl=''))
      .map(func=lambda x: -int(match.group(1)) if (match := re.fullmatch(pattern=r'\((\d+)\)', string=x.strip())) else x.strip())
      .map(func=lambda x: 0 if x == '-' else x))
df.head()

,period,product_type,sales_office,sales_volume,gross_sales,raw_materials,packaging,other_direct_cost,variable_manufacturing,fixed_manufacturing,warehouse,trans_primary,trans_delivery
0,2022-M01,CAN CF,South,86713,620364,2233480002,153200,5417,14429,36212,7465,9044,10965
1,2022-M01,CAN CF,South,192462,1350768,4957263365,340031,12022,32026,80373,16568,20073,24337
2,2022-M01,CAN CF,South,77879,554108,2005942650,137593,4865,12959,32523,6704,8122,9848
3,2022-M01,CAN CF,Central,132807,939619,3420718705,234635,8296,22099,55461,11433,13851,16793
4,2022-M01,CAN CF,North,27914,205169,718979125,49317,1744,4645,11657,2403,2911,3530

In [7]:
df[df.iloc[:, 3:].map(func=lambda x: pd.to_numeric(arg=x, errors='coerce')).isna().any(axis=1)]

,period,product_type,sales_office,sales_volume,gross_sales,raw_materials,packaging,other_direct_cost,variable_manufacturing,fixed_manufacturing,warehouse,trans_primary,trans_delivery
995,2022-M01,PET CF,South,#VALUE!,#VALUE!,#VALUE!,#VALUE!,#VALUE!,#VALUE!,#VALUE!,#VALUE!,#REF!,#REF!
2404,2022-M03,PET HF,South,#REF!,#REF!,#REF!,#REF!,#REF!,#REF!,#REF!,#REF!,#REF!,#REF!

In [8]:
df.drop(index=[995, 2404], inplace=True)
df.head()

,period,product_type,sales_office,sales_volume,gross_sales,raw_materials,packaging,other_direct_cost,variable_manufacturing,fixed_manufacturing,warehouse,trans_primary,trans_delivery
0,2022-M01,CAN CF,South,86713,620364,2233480002,153200,5417,14429,36212,7465,9044,10965
1,2022-M01,CAN CF,South,192462,1350768,4957263365,340031,12022,32026,80373,16568,20073,24337
2,2022-M01,CAN CF,South,77879,554108,2005942650,137593,4865,12959,32523,6704,8122,9848
3,2022-M01,CAN CF,Central,132807,939619,3420718705,234635,8296,22099,55461,11433,13851,16793
4,2022-M01,CAN CF,North,27914,205169,718979125,49317,1744,4645,11657,2403,2911,3530

### **3. Feature engineering**

In [9]:
df['month'] = df['period'].str.split(pat='M').str[1]
df.drop(columns='period', inplace=True)
df.head()

,product_type,sales_office,sales_volume,gross_sales,raw_materials,packaging,other_direct_cost,variable_manufacturing,fixed_manufacturing,warehouse,trans_primary,trans_delivery,month
0,CAN CF,South,86713,620364,2233480002,153200,5417,14429,36212,7465,9044,10965,01
1,CAN CF,South,192462,1350768,4957263365,340031,12022,32026,80373,16568,20073,24337,01
2,CAN CF,South,77879,554108,2005942650,137593,4865,12959,32523,6704,8122,9848,01
3,CAN CF,Central,132807,939619,3420718705,234635,8296,22099,55461,11433,13851,16793,01
4,CAN CF,North,27914,205169,718979125,49317,1744,4645,11657,2403,2911,3530,01

### **4. Change data type**

In [10]:
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.dtypes

product_type              object
sales_office              object
sales_volume               int64
gross_sales                int64
raw_materials              int64
packaging                  int64
other_direct_cost          int64
variable_manufacturing     int64
fixed_manufacturing        int64
warehouse                  int64
trans_primary              int64
trans_delivery             int64
month                      int64
dtype: object

## **IV. Data exporting**

In [11]:
df.to_csv(path_or_buf='data/cleaned_data.csv', index=False)